//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koffeinfrei.MinusShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Koffeinfrei.MinusShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All uploads complete, saving gallery....
        /// </summary>
        public static string AllUploadSuccessful {
            get {
                return ResourceManager.GetString("AllUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create gallery. .
        /// </summary>
        public static string CreateGalleryFailed {
            get {
                return ResourceManager.GetString("CreateGalleryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery created. .
        /// </summary>
        public static string GalleryCreated {
            get {
                return ResourceManager.GetString("GalleryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery saved..
        /// </summary>
        public static string GallerySaved {
            get {
                return ResourceManager.GetString("GallerySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;.
        /// </summary>
        public static string InputTitleDefaultText {
            get {
                return ResourceManager.GetString("InputTitleDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this file.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save gallery. .
        /// </summary>
        public static string SaveGalleryFailed {
            get {
                return ResourceManager.GetString("SaveGalleryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TooltipCancelButton {
            get {
                return ResourceManager.GetString("TooltipCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy editor link to clipboard.
        /// </summary>
        public static string TooltipCopyEditToClipboard {
            get {
                return ResourceManager.GetString("TooltipCopyEditToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string TooltipCopyToClipboard {
            get {
                return ResourceManager.GetString("TooltipCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TooltipEmail {
            get {
                return ResourceManager.GetString("TooltipEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on facebook.
        /// </summary>
        public static string TooltipFacebook {
            get {
                return ResourceManager.GetString("TooltipFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post on identi.ca.
        /// </summary>
        public static string TooltipIdentica {
            get {
                return ResourceManager.GetString("TooltipIdentica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start sharing.
        /// </summary>
        public static string TooltipStartButton {
            get {
                return ResourceManager.GetString("TooltipStartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet it.
        /// </summary>
        public static string TooltipTwitter {
            get {
                return ResourceManager.GetString("TooltipTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed. .
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file .
        /// </summary>
        public static string UploadingFile {
            get {
                return ResourceManager.GetString("UploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading files....
        /// </summary>
        public static string UploadingFiles {
            get {
                return ResourceManager.GetString("UploadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload successful. .
        /// </summary>
        public static string UploadSuccessful {
            get {
                return ResourceManager.GetString("UploadSuccessful", resourceCulture);
            }
        }
    }
}
